# Information about where the book exists on the web
repository:
  url    : https://github.com/subhacom/moose-notebooks 
  branch : HEAD  

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

